name = "afftrack"
compatibility_date = "2024-07-01"

[build]
command = "npm install --legacy-peer-deps && npm run build"
cwd = "./"

[env.production]
name = "afftrack-prod"

[build.output]
directory = "dist"
